console.log("Hello World!!");
console.log("Hello " + "World!!");
// console.log(5);
console.log(65536);
console.log(5+3);
console.log(5*10);
console.log("10+8");
console.log(10+8);
console.log("20割る3の余りは"+20%3);
window.alert("Hello World!!");